package Principal;

import BD.BD;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Consulta extends javax.swing.JFrame {

    private String MENSAJE = "";
    static DefaultTableModel t = new DefaultTableModel();
    public static int id;
    private int TipoC = 0;
    private String fecha = "";

    public Consulta() {
        initComponents();
        t = (DefaultTableModel) jTable1.getModel();
        jDateChooser1.setEnabled(false);
        txtMatricula.setEnabled(false);
        btnAceptar2.setEnabled(false);
        LimpiaTabla();
    }

    public Consulta(int id) {
        initComponents();
        t = (DefaultTableModel) jTable1.getModel();
        jDateChooser1.setEnabled(false);
        txtMatricula.setEnabled(false);
        btnAceptar2.setEnabled(false);
        LimpiaTabla();
        Consulta.id = id;
    }

    /**
     * icono de la aplicación
     * @return 
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagen/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoConsulta = new javax.swing.ButtonGroup();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelRoundTranslucido1 = new org.edisoncor.gui.panel.PanelRoundTranslucido();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnAceptar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txttitulo = new javax.swing.JLabel();
        jRadioMatricula = new javax.swing.JRadioButton();
        jRadioPorFechMat = new javax.swing.JRadioButton();
        jRadioFecha = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas ");
        setBackground(new java.awt.Color(102, 0, 0));
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoToConsultas.jpg"))); // NOI18N

        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Fecha");

        btnAceptar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/accept.png"))); // NOI18N
        btnAceptar2.setText("Buscar");
        btnAceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRoundTranslucido1Layout = new javax.swing.GroupLayout(panelRoundTranslucido1);
        panelRoundTranslucido1.setLayout(panelRoundTranslucido1Layout);
        panelRoundTranslucido1Layout.setHorizontalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundTranslucido1Layout.createSequentialGroup()
                .addGap(0, 244, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar2)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panelRoundTranslucido1Layout.setVerticalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundTranslucido1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnAceptar2)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap(789, Short.MAX_VALUE)
                .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N.P", "Matrícula", "Nombre", "Práctica", "HoraEntrada", "HoraSalida", "Sustituye", "Grupo", "Fecha"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        txttitulo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        txttitulo.setForeground(new java.awt.Color(102, 0, 0));
        txttitulo.setText("Consultas");

        jRadioMatricula.setBackground(new java.awt.Color(153, 153, 255));
        TipoConsulta.add(jRadioMatricula);
        jRadioMatricula.setText("Por matrícula");
        jRadioMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMatriculaActionPerformed(evt);
            }
        });

        jRadioPorFechMat.setBackground(new java.awt.Color(153, 153, 255));
        TipoConsulta.add(jRadioPorFechMat);
        jRadioPorFechMat.setText("Por matrícula y fecha");
        jRadioPorFechMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPorFechMatActionPerformed(evt);
            }
        });

        jRadioFecha.setBackground(new java.awt.Color(153, 153, 255));
        TipoConsulta.add(jRadioFecha);
        jRadioFecha.setText("Por fecha");
        jRadioFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFechaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Elige como quiere realizar la consulta");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Ingresa los datos ");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Matrícula");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LogoEnfermeria.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logoUnsis.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioPorFechMat)
                                .addGap(34, 34, 34)
                                .addComponent(jRadioFecha))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioMatricula)
                            .addComponent(jRadioPorFechMat)
                            .addComponent(jRadioFecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addGap(131, 131, 131)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jRadioMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMatriculaActionPerformed
        TipodeConsulta();
    }//GEN-LAST:event_jRadioMatriculaActionPerformed

    private void btnAceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar2ActionPerformed
        consultas();
    }//GEN-LAST:event_btnAceptar2ActionPerformed

    private void jRadioPorFechMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPorFechMatActionPerformed
        TipodeConsulta();
    }//GEN-LAST:event_jRadioPorFechMatActionPerformed

    private void jRadioFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFechaActionPerformed
        TipodeConsulta();
    }//GEN-LAST:event_jRadioFechaActionPerformed

    private void txtMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyTyped

        char validar = evt.getKeyChar();
        if (!(validar >= 48 && validar <= 57) || !(validar != 127)) {
            evt.consume();
        }
        if (txtMatricula.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMatriculaKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Regresa al menú principal enviando el idUsuario para los permisos
        MenuPrincipal menu;
        menu = new MenuPrincipal(id);
        menu.show();
        this.dispose();


    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TipoConsulta;
    private javax.swing.JButton btnAceptar2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioFecha;
    private javax.swing.JRadioButton jRadioMatricula;
    private javax.swing.JRadioButton jRadioPorFechMat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelRoundTranslucido panelRoundTranslucido1;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JLabel txttitulo;
    // End of variables declaration//GEN-END:variables

// Método para activar y desactivar componentes
    private void TipodeConsulta() {
        btnAceptar2.setEnabled(true);
        LimpiarComponentes();
        if (jRadioMatricula.isSelected()) {
            txtMatricula.setEnabled(true);
            jDateChooser1.setEnabled(false);
            TipoC = 1;
        } else if (jRadioPorFechMat.isSelected()) {
            jDateChooser1.setEnabled(true);
            txtMatricula.setEnabled(true);
            TipoC = 2;

        } else if (jRadioFecha.isSelected()) {
            txtMatricula.setEnabled(false);
            jDateChooser1.setEnabled(true);
            TipoC = 3;

        }
        jDateChooser1.getDateEditor().setEnabled(false);
    }

// Método para limpiar los componentes
    private void LimpiarComponentes() {
        txtMatricula.setText(null);
        jDateChooser1.setDate(null);
    }

// depende el tipo de consulta le corresponde un query diferente, el resultado es agregado a la tabla
    private void consultas() {
        LimpiaTabla();
        String sql;
        Object[] ob = new Object[11];
        int j = 1;
        switch (TipoC) {
            case 1:
                sql = "call spMostrarConsultaRePorMatricula('" + txtMatricula.getText() + "')";
                break;
            case 2:
                fecha = formatoFecha(jDateChooser1);
                sql = "call spMostrarConsultaRePorMatriculaYFecha('" + txtMatricula.getText() + "','" + fecha + "')";
                break;
            default:
                fecha = formatoFecha(jDateChooser1);
                sql = "call spMostrarConsultaRePorFecha('" + fecha + "')";
                break;
        }
        ResultSet r = consulta(sql);
        try {
            while (r.next()) {
                // EXIST = true; // para después verificar si existen datos para poder generar el reporte
                ob[0] = j;
                ob[1] = r.getObject("Matricula");
                ob[2] = r.getObject("Nombre");
                ob[3] = r.getObject("Practica");
                ob[4] = r.getObject("HoraEntrada");
                ob[5] = r.getObject("HoraSalida");
                ob[6] = r.getObject("Sustituye");
                ob[7] = r.getObject("Grupo");
                ob[8] = r.getObject("Fecha");
                t.addRow(ob);
                j++;
            }
        } catch (SQLException e) {
            System.err.println(MENSAJE + "\n Error\n" + sql);
        }
        // agrega los datos a la tabla (jTable)
        jTable1.setModel(t);
        JOptionPane.showMessageDialog(null, "La consulta fue realizada");
    }

// función que obtiene el formato del JDate Chooser y lo formatea para poder ingresarlo a la Base de datos.
    public static String formatoFecha(JDateChooser jDatefecha) {
        String fecha = "";
        try {
            String dia = Integer.toString(jDatefecha.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(jDatefecha.getCalendar().get(Calendar.MONTH) + 1);
            String year = Integer.toString(jDatefecha.getCalendar().get(Calendar.YEAR));
            fecha = (year + "-" + mes + "-" + dia);
            return fecha;
        } catch (Exception e) {
            System.out.println("Hubo un error formateando fecha");
        }
        return fecha;
    }
    
    /**
     * limpia la tabla para nuevas consultas
     */
    public static void LimpiaTabla() {
        int a = t.getRowCount();

        while (a != 0) { // Ciclo para Borrar la Tabla 1
            if (a != 0) {
                t.removeRow(0);
            }
            a = t.getRowCount();
        }
    }

    public ResultSet consulta(String consul){

        ResultSet r = null;
        MENSAJE = "";
        try {
            BD bd = new BD();
            Statement stm = bd.conecta().createStatement();
            r = stm.executeQuery(consul);
        } catch (SQLException e) {
            MENSAJE = e.getMessage();
        }
        return r;
    }

}
